language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules
  yarn: true

notifications:
  email:
    on_success: never

script:
  - npm test
  - npm run lint
  - npm run codecov

deploy:
  - provider: script
    script: tools/publish.sh
    on:
      tags: true
