language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules
  yarn: true

notifications:
  email:
    on_success: never

before_script:
  - npm prune

script:
  - npm test
  - npm run coverage

deploy:
  - provider: script
    script: tools/publish.sh
    on:
      tags: true
