# https://github.com/JoshuaWise/better-sqlite3/blob/v2.0.1/.travis.yml
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules
  yarn: true

notifications:
  email:
    on_success: never

before_install:
  - export CC="gcc-4.9" CXX="g++-4.9"

before_script:
  - npm prune

script:
  - npm test
  - npm run lint
  - npm run codecov

deploy:
  - provider: script
    script: tools/publish.sh
    on:
      tags: true
