language: node_js
node_js:
  - "6"

env:
  - ACTION=test
  - ACTION=coverage

script:
  - npm run $ACTION

deploy:
  - provider: script
    script: tools/publish.sh
    on:
      tags: true

notifications:
  email:
    on_success: never
