language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules
  yarn: true

notifications:
  email: false

before_script:
  - npm prune

script:
  - npm test
  - npm run coverage

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
