name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node:
          - 14
          - 16
          - 18
          - 20
    name: Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - run: yarn coverage
        if: matrix.node == 18
      - name: Upload coverage to Codecov
        if: matrix.node == 18
        uses: codecov/codecov-action@v3.1.4
        with:
          directory: ./coverage/
          fail_ci_if_error: true
          name: codecov
          verbose: true
